name: Terraform Pipeline

on:
  push:
    branches:
      - develop  

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.3.0 

      - name: Set environment variables
        run: |
          echo "IC_API_KEY=${{ secrets.IC_API_KEY }}" >> $GITHUB_ENV
          echo "IAAS_CLASSIC_USERNAME=${{ secrets.IAAS_CLASSIC_USERNAME }}" >> $GITHUB_ENV
          echo "IAAS_CLASSIC_API_KEY=${{ secrets.IAAS_CLASSIC_API_KEY }}" >> $GITHUB_ENV

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve
